# Generated by Django 3.0.3 on 2020-06-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('is_complete', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
